# Generated by Django 3.1.5 on 2021-03-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_selected',
            field=models.BooleanField(default=True),
        ),
    ]
