# Generated by Django 3.1.5 on 2021-02-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brief_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
