# Generated by Django 3.1.5 on 2021-02-15 16:49

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210212_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpeg', stdimage.models.JPEGField(upload_to='path/to/img')),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='path/to/img')),
            ],
        ),
    ]
