# Generated by Django 3.1.5 on 2021-02-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
