# Generated by Django 3.1.5 on 2021-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='owner_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
